"""added image url

Revision ID: 1549c418f426
Revises: 290aabcf2d0c
Create Date: 2025-06-30 01:21:06.486777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1549c418f426'
down_revision = '290aabcf2d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
